export enum AppRoute {
	HOME = '/',
	Chocolate = '/chocolate',
	Candy = '/candy',
	Coctail = '/coctail',
	Sets = '/sets',
	SpecialSeries = '/special-series',
	ABOUT = '/about',
	DELIVERY = '/delivery',
	CONTACTS = '/contacts',
	PAYMENT = '/payment',
	POLITIC = '/politic',
	AUTH = '/auth',
	REGISTRATION = 'registration',
}
