export enum AppRoute {
	HOME = '/',
	LK = '/lk',
	LKinfo = '/info',
	LKfavorite = '/favorite',
	LKorders = '/orders',
	LKcart = '/cart',
	Chocolate = '/chocolate',
	Candy = '/candy',
	Coctail = '/coctail',
	Sets = '/sets',
	SpecialSeries = '/special-series',
	ABOUT = '/about',
	DELIVERY = '/delivery',
	CONTACTS = '/contacts',
	PAYMENT = '/payment',
	POLITIC = '/politic',
	AUTH = '/auth',
	REGISTRATION = 'registration',
	Catalog = '/catalog',
	CatalogItem = '/item',
}
